spring:
  application:
    name: GildedRoseKata
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gildedrose

elasticsearch:
  host: localhost
  port: 9300
  clustername: elasticsearch
